"""Execution-layer seam between semantic authority and numerical runtimes."""

from trellis.execution.compiler import (
    UnsupportedExecutionSemantics,
    compile_contract_execution_ir,
    compile_contract_ir_execution_ir,
    compile_dynamic_execution_ir,
    compile_semantic_execution_ir,
    compile_static_leg_execution_ir,
    infer_source_track,
)
from trellis.execution.ir import (
    ContractExecutionIR,
    ContingentSettlement,
    CouponLegExecution,
    CurveQuoteObservableRef,
    DecisionAction,
    DecisionProgram,
    ExecutionEvent,
    ExecutionEventPlan,
    ExecutionIRWellFormednessError,
    ExecutionMetadata,
    ExecutionObligation,
    ExecutionStateField,
    ExecutionStateSchema,
    ForwardRateObservableRef,
    KnownCashflowObligation,
    ObservableBinding,
    PeriodRateOptionStripExecution,
    PrincipalExchange,
    RequirementHints,
    SettlementProgram,
    SettlementStep,
    SourceTrack,
    SpotObservableRef,
    SurfaceQuoteObservableRef,
    SwapRateObservableRef,
)
from trellis.execution.summary import contract_execution_summary

__all__ = [
    "ContractExecutionIR",
    "ContingentSettlement",
    "CouponLegExecution",
    "CurveQuoteObservableRef",
    "DecisionAction",
    "DecisionProgram",
    "ExecutionEvent",
    "ExecutionEventPlan",
    "ExecutionIRWellFormednessError",
    "ExecutionMetadata",
    "ExecutionObligation",
    "ExecutionStateField",
    "ExecutionStateSchema",
    "ForwardRateObservableRef",
    "KnownCashflowObligation",
    "ObservableBinding",
    "PeriodRateOptionStripExecution",
    "PrincipalExchange",
    "RequirementHints",
    "SettlementProgram",
    "SettlementStep",
    "SourceTrack",
    "SpotObservableRef",
    "SurfaceQuoteObservableRef",
    "SwapRateObservableRef",
    "UnsupportedExecutionSemantics",
    "compile_contract_execution_ir",
    "compile_contract_ir_execution_ir",
    "compile_dynamic_execution_ir",
    "compile_semantic_execution_ir",
    "compile_static_leg_execution_ir",
    "contract_execution_summary",
    "infer_source_track",
]
