"""Execution-layer seam between semantic authority and numerical runtimes."""

from trellis.execution.admission import (
    ExecutionCapabilityAdmission,
    ExecutionCapabilityBlocker,
    admit_execution_capabilities,
)
from trellis.execution.compiler import (
    UnsupportedExecutionSemantics,
    compile_bermudan_best_of_basket_execution_ir,
    compile_contract_execution_ir,
    compile_contract_ir_execution_ir,
    compile_dynamic_execution_ir,
    compile_semantic_execution_ir,
    compile_static_leg_execution_ir,
    infer_source_track,
)
from trellis.execution.ir import (
    ContractExecutionIR,
    ContingentSettlement,
    CouponLegExecution,
    CurveQuoteObservableRef,
    DecisionAction,
    DecisionProgram,
    ExecutionEvent,
    ExecutionEventPlan,
    ExecutionIRWellFormednessError,
    ExecutionMetadata,
    ExecutionObligation,
    ExecutionStateField,
    ExecutionStateSchema,
    ForwardRateObservableRef,
    KnownCashflowObligation,
    ObservableBinding,
    PeriodRateOptionStripExecution,
    PrincipalExchange,
    RequirementHints,
    SettlementProgram,
    SettlementStep,
    SourceTrack,
    SpotObservableRef,
    SurfaceQuoteObservableRef,
    SwapRateObservableRef,
)
from trellis.execution.shims import price_bermudan_best_of_basket_from_compat_spec
from trellis.execution.summary import contract_execution_summary
from trellis.execution.visitors import (
    BermudanBestOfBasketLatticeControls,
    BermudanBestOfBasketLatticeResult,
    BermudanBestOfBasketMCControls,
    BermudanBestOfBasketMCInputs,
    BermudanBestOfBasketMCResult,
    price_bermudan_best_of_basket_lattice,
    price_bermudan_best_of_basket_monte_carlo,
)

__all__ = [
    "BermudanBestOfBasketLatticeControls",
    "BermudanBestOfBasketLatticeResult",
    "BermudanBestOfBasketMCControls",
    "BermudanBestOfBasketMCInputs",
    "BermudanBestOfBasketMCResult",
    "ContractExecutionIR",
    "ContingentSettlement",
    "CouponLegExecution",
    "CurveQuoteObservableRef",
    "DecisionAction",
    "DecisionProgram",
    "ExecutionCapabilityAdmission",
    "ExecutionCapabilityBlocker",
    "ExecutionEvent",
    "ExecutionEventPlan",
    "ExecutionIRWellFormednessError",
    "ExecutionMetadata",
    "ExecutionObligation",
    "ExecutionStateField",
    "ExecutionStateSchema",
    "ForwardRateObservableRef",
    "KnownCashflowObligation",
    "ObservableBinding",
    "PeriodRateOptionStripExecution",
    "PrincipalExchange",
    "RequirementHints",
    "SettlementProgram",
    "SettlementStep",
    "SourceTrack",
    "SpotObservableRef",
    "SurfaceQuoteObservableRef",
    "SwapRateObservableRef",
    "UnsupportedExecutionSemantics",
    "admit_execution_capabilities",
    "compile_bermudan_best_of_basket_execution_ir",
    "compile_contract_execution_ir",
    "compile_contract_ir_execution_ir",
    "compile_dynamic_execution_ir",
    "compile_semantic_execution_ir",
    "compile_static_leg_execution_ir",
    "contract_execution_summary",
    "infer_source_track",
    "price_bermudan_best_of_basket_from_compat_spec",
    "price_bermudan_best_of_basket_lattice",
    "price_bermudan_best_of_basket_monte_carlo",
]
