"""Analytics: OAS, z-spread, risk factors, and other derived measures."""

from trellis.analytics.portfolio_aad import (
    AADSupportDecision,
    ArithmeticAsianOptionVolAADAdapter,
    BondCurveAADAdapter,
    BondCurveAADMarketContext,
    DefaultUnsupportedAADPolicy,
    PortfolioAADRequest,
    PortfolioAADResult,
    QuantoCorrelationAADAdapter,
    QuantoCorrelationAADMarketContext,
    TradeAADAdapter,
    UnsupportedAADPosition,
    VanillaEquityOptionVolAADAdapter,
    VanillaEquityOptionVolAADMarketContext,
)
from trellis.analytics.portfolio_aad_admission import (
    PortfolioAADFactorRequirement,
    PortfolioAADLaneAdmission,
    admit_portfolio_aad_lane,
)
from trellis.analytics.hybrid_ad_admission import (
    HybridADFactorRequirement,
    HybridADLaneAdmission,
    admit_hybrid_ad_lane,
)
from trellis.analytics.hybrid_factors import (
    HybridDependencyNode,
    HybridFactorGraph,
    HybridUnsupportedDependency,
    MarketObjectCoordinateChart,
)
from trellis.analytics.hybrid_ad import (
    HybridCorrelationStructureRequest,
    HybridDerivativeRequest,
    HybridDerivativeResult,
    HybridMatrixCoordinateContext,
    build_correlation_matrix_coordinate_context,
    differentiate_quanto_correlation_matrix,
    differentiate_quanto_scalar_correlation,
    differentiate_quanto_scalar_inputs,
    fail_closed_correlation_structure_derivative,
)
from trellis.analytics.risk_factors import (
    RiskAggregationMap,
    RiskFactorCoordinate,
    RiskFactorId,
    RiskFactorRegistry,
    SparseRiskVector,
    UnsupportedRiskFactorObject,
)

__all__ = [
    "AADSupportDecision",
    "ArithmeticAsianOptionVolAADAdapter",
    "BondCurveAADAdapter",
    "BondCurveAADMarketContext",
    "DefaultUnsupportedAADPolicy",
    "HybridADFactorRequirement",
    "HybridADLaneAdmission",
    "HybridCorrelationStructureRequest",
    "HybridDependencyNode",
    "HybridDerivativeRequest",
    "HybridDerivativeResult",
    "HybridFactorGraph",
    "HybridMatrixCoordinateContext",
    "HybridUnsupportedDependency",
    "MarketObjectCoordinateChart",
    "PortfolioAADRequest",
    "PortfolioAADResult",
    "PortfolioAADFactorRequirement",
    "PortfolioAADLaneAdmission",
    "QuantoCorrelationAADAdapter",
    "QuantoCorrelationAADMarketContext",
    "RiskAggregationMap",
    "RiskFactorCoordinate",
    "RiskFactorId",
    "RiskFactorRegistry",
    "SparseRiskVector",
    "TradeAADAdapter",
    "UnsupportedAADPosition",
    "UnsupportedRiskFactorObject",
    "VanillaEquityOptionVolAADAdapter",
    "VanillaEquityOptionVolAADMarketContext",
    "admit_hybrid_ad_lane",
    "admit_portfolio_aad_lane",
    "build_correlation_matrix_coordinate_context",
    "differentiate_quanto_correlation_matrix",
    "differentiate_quanto_scalar_correlation",
    "differentiate_quanto_scalar_inputs",
    "fail_closed_correlation_structure_derivative",
]
