"""Deterministic callable-bond payoff adapter.

This generated surface now stays intentionally thin: it only translates the
string-based generated spec into the reusable reference implementation in
``trellis.instruments.callable_bond``.
"""

from __future__ import annotations

from functools import cached_property
from dataclasses import dataclass
from datetime import date

from trellis.core.market_state import MarketState
from trellis.core.types import DayCountConvention, Frequency
from trellis.instruments.callable_bond import (
    CallableBondPayoff as ReferenceCallableBondPayoff,
    CallableBondSpec as ReferenceCallableBondSpec,
)


@dataclass(frozen=True)
class CallableBondSpec:
    """Specification for a callable bond generated by the agent."""

    notional: float
    coupon: float
    start_date: date
    end_date: date
    call_dates: str
    call_price: float = 100.0
    frequency: Frequency = Frequency.SEMI_ANNUAL
    day_count: DayCountConvention = DayCountConvention.ACT_365

    def to_reference_spec(self) -> ReferenceCallableBondSpec:
        """Translate the generated string-based schedule into the reusable spec."""
        call_dates = tuple(_parse_call_dates(self.call_dates))
        if not call_dates:
            raise ValueError("Callable bond adapter requires at least one call date.")
        return ReferenceCallableBondSpec(
            notional=self.notional,
            coupon=self.coupon,
            start_date=self.start_date,
            end_date=self.end_date,
            call_dates=list(call_dates),
            call_price=self.call_price,
            frequency=self.frequency,
            day_count=self.day_count,
        )


def _parse_call_dates(value: str) -> tuple[date, ...]:
    """Parse a comma-separated ISO date list into call dates."""
    parsed: list[date] = []
    for token in value.split(","):
        text = token.strip()
        if text:
            parsed.append(date.fromisoformat(text))
    return tuple(dict.fromkeys(parsed))


class CallableBondPayoff:
    """Thin adapter over the shared callable-bond reference implementation."""

    def __init__(self, spec: CallableBondSpec):
        self._spec = spec

    @property
    def spec(self) -> CallableBondSpec:
        return self._spec

    @property
    def requirements(self) -> set[str]:
        return self._requirements

    @cached_property
    def _reference_spec(self) -> ReferenceCallableBondSpec:
        """Cache the parsed reference spec because the adapter is reused hot."""
        return self._spec.to_reference_spec()

    @cached_property
    def _reference_payoff(self) -> ReferenceCallableBondPayoff:
        """Cache the shared reference payoff so repeated valuations stay thin."""
        return ReferenceCallableBondPayoff(self._reference_spec)

    @cached_property
    def _requirements(self) -> frozenset[str]:
        """Cache the immutable requirement set once instead of rebuilding it."""
        return frozenset(self._reference_payoff.requirements)

    def evaluate(self, market_state: MarketState) -> float:
        return float(self._reference_payoff.evaluate(market_state))
