"""Shared market-input resolution helpers for generated pricing routes."""

from trellis.models.resolution.basket_semantics import (
    BasketSpecLike,
    ResolvedBasketSemantics,
    resolve_basket_semantics,
)
from trellis.models.resolution.quanto import (
    ResolvedQuantoInputs,
    resolve_quanto_correlation,
    resolve_quanto_foreign_curve,
    resolve_quanto_inputs,
    resolve_quanto_underlier_spot,
)
from trellis.models.resolution.single_state_diffusion import (
    DiscountCurveLike,
    ResolvedSingleStateDiffusionInputs,
    SingleStateDiffusionMarketStateLike,
    SingleStateDiffusionSpecLike,
    VolSurfaceLike,
    gbm_log_ratio_char_fn,
    gbm_log_spot_char_fn,
    put_from_call_parity,
    resolve_single_state_diffusion_inputs,
    terminal_intrinsic_from_resolved,
)
from trellis.models.resolution.short_rate_claims import (
    DiscountBondClaimSpecLike,
    FlatShortRateVolSurface,
    ResolvedDiscountBondClaim,
    ResolvedShortRateRegime,
    ShortRateClaimMarketStateLike,
    ShortRateComparisonRegime,
    extract_short_rate_comparison_regime,
    normalize_discount_bond_strike,
    resolve_discount_bond_claim_inputs,
    resolve_discount_bond_option_type,
    resolve_short_rate_regime,
)

__all__ = [
    "ResolvedQuantoInputs",
    "BasketSpecLike",
    "ResolvedBasketSemantics",
    "resolve_basket_semantics",
    "resolve_quanto_correlation",
    "resolve_quanto_foreign_curve",
    "resolve_quanto_inputs",
    "resolve_quanto_underlier_spot",
    "DiscountCurveLike",
    "ResolvedSingleStateDiffusionInputs",
    "SingleStateDiffusionMarketStateLike",
    "SingleStateDiffusionSpecLike",
    "VolSurfaceLike",
    "gbm_log_ratio_char_fn",
    "gbm_log_spot_char_fn",
    "put_from_call_parity",
    "resolve_single_state_diffusion_inputs",
    "terminal_intrinsic_from_resolved",
    "DiscountBondClaimSpecLike",
    "FlatShortRateVolSurface",
    "ResolvedDiscountBondClaim",
    "ResolvedShortRateRegime",
    "ShortRateClaimMarketStateLike",
    "ShortRateComparisonRegime",
    "extract_short_rate_comparison_regime",
    "normalize_discount_bond_strike",
    "resolve_discount_bond_claim_inputs",
    "resolve_discount_bond_option_type",
    "resolve_short_rate_regime",
]
