"""Git working-tree cleanliness helpers for benchmark runners.

Benchmark history records stamp ``git_sha`` from the last commit.  If the
working tree carries uncommitted changes the recorded sha does not describe
the code that actually produced the artifact, which in turn makes the
QUA-867 admission gate trust provenance it should not.  These helpers let a
CLI refuse to run against a dirty tree, or (with explicit opt-in) record the
dirty status alongside the sha so downstream audits can tell the difference.

Refs: QUA-871 (epic QUA-869).
"""

from __future__ import annotations

import subprocess
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path


# Paths under these prefixes are regenerated by routine benchmark/test activity
# and do not indicate the source tree has been edited.  Keep the list small and
# justified — a broad allowlist defeats the purpose of the gate.
_DEFAULT_CLEAN_IGNORE_PREFIXES: tuple[str, ...] = (
    "task_runs/",
    "trellis/agent/knowledge/traces/",
    "trellis.egg-info/",
    "trellis_agent.egg-info/",
)


@dataclass(frozen=True)
class WorkingTreeStatus:
    """Result of inspecting the working tree for uncommitted source edits."""

    clean: bool
    dirty_paths: tuple[str, ...]

    def as_record(self) -> dict[str, object]:
        return {
            "clean": self.clean,
            "dirty_paths": list(self.dirty_paths),
        }


class DirtyWorkingTreeError(RuntimeError):
    """Raised when a benchmark runner refuses to execute against a dirty tree."""


def inspect_working_tree(
    repo_root: Path,
    *,
    ignore_prefixes: Iterable[str] = _DEFAULT_CLEAN_IGNORE_PREFIXES,
) -> WorkingTreeStatus:
    """Return whether the working tree carries source edits outside ignored paths."""
    prefixes = tuple(str(prefix).strip().replace("\\", "/") for prefix in ignore_prefixes)
    completed = subprocess.run(
        ["git", "status", "--porcelain", "--untracked-files=all"],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        # A non-git tree is treated as clean; the caller can still record the sha
        # as "unknown" via the normal revisions path.
        return WorkingTreeStatus(clean=True, dirty_paths=())
    dirty_paths: list[str] = []
    seen: set[str] = set()
    for raw_line in completed.stdout.splitlines():
        if len(raw_line) <= 3:
            continue
        # Rename entries look like ``old -> new``.  Both sides matter:
        # if the source path is outside the ignore list (e.g. a tracked
        # source file moved into `task_runs/`), the rename is dirty even
        # when the destination falls under an ignored prefix.
        # (PR #590 Codex P2 review.)
        raw_path = raw_line[3:].strip()
        if " -> " in raw_path:
            old, new = raw_path.split(" -> ", 1)
            entries = [old.strip(), new.strip()]
        else:
            entries = [raw_path]
        for candidate in entries:
            normalized = candidate.strip("\"").strip().replace("\\", "/")
            if not normalized:
                continue
            if any(normalized.startswith(prefix) for prefix in prefixes):
                continue
            if normalized in seen:
                continue
            seen.add(normalized)
            dirty_paths.append(normalized)
    return WorkingTreeStatus(
        clean=not dirty_paths,
        dirty_paths=tuple(dirty_paths),
    )


def enforce_clean_tree(
    repo_root: Path,
    *,
    allow_dirty: bool = False,
    ignore_prefixes: Iterable[str] = _DEFAULT_CLEAN_IGNORE_PREFIXES,
) -> WorkingTreeStatus:
    """Inspect the working tree and raise ``DirtyWorkingTreeError`` if dirty.

    ``allow_dirty=True`` returns the status without raising so the caller can
    flag ``dirty_tree=true`` in its emitted records.
    """
    status = inspect_working_tree(repo_root, ignore_prefixes=ignore_prefixes)
    if status.clean or allow_dirty:
        return status
    joined = ", ".join(status.dirty_paths[:10])
    more = "" if len(status.dirty_paths) <= 10 else f" (+{len(status.dirty_paths) - 10} more)"
    raise DirtyWorkingTreeError(
        "QUA-871: refusing to run benchmark against a dirty tree; "
        "commit or stash first, or pass --allow-dirty to record the run as "
        f"untrusted. Dirty paths: {joined}{more}"
    )


__all__ = (
    "DirtyWorkingTreeError",
    "WorkingTreeStatus",
    "enforce_clean_tree",
    "inspect_working_tree",
)
